### ISSUE TITLE
Falha na autenticação com senha correta

### ISSUE THREAD

**Issue by vhns** [ElviajeroO/Eventy#1]
Mesmo autenticado com a senha correta, há retorno de 'ndeu' por parte do PHP.

Segue etapas de reprodução de erro:

Criar uma conta na página de cadastro
Tentar logar logar com a conta na página de autenticação
Verificar retorno em response de autenticacao.php na aba de network do navegador

Print abaixo:

![image](https://github.com/ElviajeroO/Eventy/assets/42123715/208697c0-0c88-4152-ab53-24f78e5b8121)
![image](https://github.com/ElviajeroO/Eventy/assets/42123715/0d2f62c4-5eee-476f-ac06-2081f8ef0b3f)

**Comment by MateusADaniel** [comment]
Puta irresposabilidade meu, travou a sprint!!!!
![Untitled](https://github.com/ElviajeroO/Eventy/assets/129968856/898cf8b3-9a09-405b-b4e0-5a5af24d0086)

**Comment by MateusADaniel** [comment]
#
